#!/bin/sh
#
# Start/stop dhcpcd
#

DAEMON=/sbin/dhcpcd
CONFIG=/etc/dhcpcd.conf
PIDFILE=/var/run/dhcpcd/pid

[ -f $CONFIG ] || exit 0

# Check if static IP is configured in cmdline
# Format: ip=<client-ip>:<server-ip>:<gateway-ip>:<netmask>::<device>:off
# Skip DHCP if static IP parameters are found
if ! grep -q "ip=[0-9.]\+:[0-9.]\+:[0-9.]\+:[0-9.]\+::eth0:off" /proc/cmdline; then
	case "$1" in
	start)
		echo "Starting dhcpcd..."
		start-stop-daemon -S -x "$DAEMON" -p "$PIDFILE" -- -f "$CONFIG"
		;;
	stop)
		echo "Stopping dhcpcd..."
		start-stop-daemon -K -x "$DAEMON" -p "$PIDFILE" -o
		;;
	reload|force-reload)
		echo "Reloading dhcpcd configuration..."
		"$DAEMON" -s reload
		;;
	restart)
		"$0" stop
		sleep 1 # Prevent race condition: ensure dhcpcd stops before start.
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|force-reload}"
		exit 1
	esac
else
	echo "Static IP found in cmdline, skipping DHCP"
	exit 0
fi
