#!/bin/sh

set_lan_led_by_name() {
        local net_card_name="$1"
        echo $net_card_name > /sys/class/leds/lan0-led1/device_name || true
        echo 0 > /sys/class/leds/lan0-led1/link || true
        echo 1 > /sys/class/leds/lan0-led1/link_1000 || true
        echo 1 > /sys/class/leds/lan0-led1/link_100 || true
        echo 1 > /sys/class/leds/lan0-led1/link_10 || true
        echo 0 > /sys/class/leds/lan0-led1/tx || true
        echo 0 > /sys/class/leds/lan0-led1/rx || true

        echo $net_card_name > /sys/class/leds/lan0-led2/device_name || true
        echo 0 > /sys/class/leds/lan0-led2/link || true
        echo 0 > /sys/class/leds/lan0-led2/link_1000 || true
        echo 0 > /sys/class/leds/lan0-led2/link_100 || true
        echo 0 > /sys/class/leds/lan0-led2/link_10 || true
        echo 1 > /sys/class/leds/lan0-led2/tx || true
        echo 1 > /sys/class/leds/lan0-led2/rx || true
}

set_lan_led() {
        local net_card=$(ip addr | grep -E '^[0-9]+:' | awk '{print $2}' | sed 's/://g' | grep -E '^en|^eth' | grep -v '^lo$')
        echo "$net_card" | while IFS= read -r line; do
                set_lan_led_by_name $line
        done
}

setup()
{
        sleep 10
        model=`cat /sys/firmware/devicetree/base/model | grep -a MUSE-Pi-Pro`
        if [ -n "$model" ]; then
                set_lan_led || true
        fi
}

clean()
{
        echo "lan led nothing to do for clean"
}

OPT=$1
case "$1" in
    start)
        setup
        ;;
    stop)
        clean
        ;;
    restart|reload)
        clean
        setup
        ;;
    *)
        echo "Usage: $0 {start|stop|reload}"
        exit 1
esac
exit $?